### PR TITLE
Integration of a new file search.

### PR DESCRIPTION
**Pull request by AlphaOneWhiskeyFour**
The integration of the DirectoryIterator offers a higher level of processing and allows you to skip hidden files.

### CODE REVIEW

**Comment by adriengibrat** [comment]
:+1: LGTM
N.B. Skiping hidden directories & files could be an method parmeter as this change the current behaviour

**Comment by xxalfa** [comment]
Glad to hear that my proposal pleases. In my branch I plan even more - I want to include or exclude objects with wildcards. Then I would like to have one parameter do a single processing, where 10 objects become 10 different torrent files.

**Comment by adriengibrat** [comment]
Do you prefer to merge frequently or to wait till your branch contains the parameter handling ?

**Comment by xxalfa** [comment]
If there are more active developers, then we can often merge. Otherwise, I would first take care of the parameter integration.

**Comment by Machou** [comment]
@xxalfa nice idea, any news of you're developpement ? :)

**Comment by Machou** [comment]
@xxalfa ok :)

**Review by darkalchemy — COMMENTED** [review]
This change would do what you want without breaking BC and without the need for the additional class.
```
    public static function scandir($dir, bool $include_hidden = true)
    {
        $paths = [];
        $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir,
            RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST);
        foreach ($iterator as $name => $object) {
            if (is_dir($name) || (!$include_hidden && basename($name)[0] === '.')) {
                continue;
            }
            $ext = pathinfo($name, PATHINFO_EXTENSION);
            if ($ext === 'torrent') {
                $paths[] = $object->getPathname();
            }
        }
        return $paths;
    }
```

**Comment by xxalfa** [comment]
@darkalchemy Thank you for your suggestion, but your approach was not yet finished, files in hidden folders would still be included. I would like to use the regex iterator, but my approach doesn't work yet. I have now found a compromise. And the SELF_FIRST parameter cannot be used, because empty folders are not included in the torrent file.

**Comment by darkalchemy** [comment]
If you look closely,  a parameter was added, simply call it with the second parameter false and the hidden files will not be included. 
I also created another branch so you could look and see how it works.  I verified that hidden files can be included or not.

**Comment by darkalchemy** [comment]
Maybe I have misunderstood the purpose of that method.. I have not used it before looking at your requested changes. I will tonight.

**Comment by darkalchemy** [comment]
I have updated the changes/demo branch. Please look and see if this does what you have desired.

I have replaced ```SELF_FIRST``` with ```LEAVES_ONLY```, so no folder names are included.
```
RecursiveIteratorIterator::LEAVES_ONLY - The default. Lists only leaves in iteration.
```

I changed the constructor, adding $include_hidden with a default value of true, so not to break BC. To not include them, just set it to false when you instantiate the class and it carries all the way through to scandir.

If I have missed something, please elaborate so that I may understand better.
Thanks

**Pull request closed without merging**
